name: github-act
on: [push, pull_request]
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: initial
      uses: actions/checkout@v6
      run: echo "action conducted successfully"
